// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBInu7Gey0oNm90vqZnW0AHOM_-Z1eDzWM',
    appId: '1:991713497116:web:5a5c241d69e2ea18704fd9',
    messagingSenderId: '991713497116',
    projectId: 'orderease-832b3',
    authDomain: 'orderease-832b3.firebaseapp.com',
    storageBucket: 'orderease-832b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1E2cH0Ku0innZJjdbszBIvYmuO1C2_fQ',
    appId: '1:991713497116:android:46c0aafc85e63366704fd9',
    messagingSenderId: '991713497116',
    projectId: 'orderease-832b3',
    storageBucket: 'orderease-832b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcopsJJa_y_sit2AgSy6aDHmnQr9KfZw',
    appId: '1:991713497116:ios:849d1b8ea3029ee8704fd9',
    messagingSenderId: '991713497116',
    projectId: 'orderease-832b3',
    storageBucket: 'orderease-832b3.appspot.com',
    iosClientId: '991713497116-lppk16iptcvcvs446c9qoie66edluq3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ordereaseNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCcopsJJa_y_sit2AgSy6aDHmnQr9KfZw',
    appId: '1:991713497116:ios:5f33f5d9c243b53f704fd9',
    messagingSenderId: '991713497116',
    projectId: 'orderease-832b3',
    storageBucket: 'orderease-832b3.appspot.com',
    iosClientId: '991713497116-1b7ieu1o6ul43lb7mjfcg2kh2eut5m8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ordereaseNew.RunnerTests',
  );
}
